/**
 * Type definitions for the Notes API.
 *
 * Lambda + API Gateway Context:
 * - These interfaces define the shape of data flowing through our serverless API.
 * - API Gateway receives JSON → Lambda parses it → we validate against these types
 *   → Lambda processes the request → returns JSON matching these shapes.
 * - TypeScript helps catch type errors at compile time, before deployment.
 *
 * Serverless Architecture Notes:
 * - Lambdas are stateless: they don't "remember" data between invocations.
 * - Data persistence happens in DynamoDB (or another AWS service), not in memory.
 * - These types represent the contract between client, Lambda, and database.
 *
 * Security & Input Validation:
 * - ALWAYS validate incoming data against these interfaces before processing.
 * - Never trust client input directly; check types, lengths, formats.
 * - Use least privilege: Lambda IAM roles should only access necessary DynamoDB
 *   tables/operations.
 */

/**
 * Represents a complete Note as stored in DynamoDB and returned to clients.
 *
 * How it flows through the system:
 * 1. Client requests a note (GET /notes/{id})
 * 2. API Gateway triggers our Lambda with event data
 * 3. Lambda reads from DynamoDB using the note ID
 * 4. DynamoDB returns raw item → we map it to this Note shape
 * 5. Lambda returns JSON response → API Gateway sends to client
 *
 * Field explanations:
 * - `id`: Unique identifier (usually UUID). Generated by Lambda on creation,
 *   never modified. Used as DynamoDB partition key for fast lookups.
 * - `title`: User-provided note title. Should be validated for length/content.
 * - `content`: Main body of the note. Can be large; consider size limits.
 * - `tags`: Array of strings for categorization. Empty array if no tags.
 * - `createdAt`: ISO 8601 timestamp string (e.g., "2025-12-23T10:30:00.000Z").
 *   Set once during creation, never changed.
 * - `updatedAt`: ISO 8601 timestamp. Updated every time the note is modified.
 *
 * Security considerations:
 * - Ensure the authenticated user owns this note before returning it.
 * - Don't expose internal database fields (like GSI keys) to clients.
 */
export interface Note {
  id: string;
  title: string;
  content: string;
  tags: string[];
  createdAt: string;
  updatedAt: string;
}

/**
 * Input data for creating a new note.
 *
 * Request lifecycle:
 * 1. Client sends POST /notes with JSON body matching this interface
 * 2. API Gateway passes the body to Lambda via event.body (as string)
 * 3. Lambda parses JSON and validates it matches CreateNoteInput
 * 4. Lambda generates `id`, `createdAt`, `updatedAt` fields
 * 5. Lambda writes complete Note to DynamoDB
 * 6. Lambda returns the created Note to the client
 *
 * Field explanations:
 * - `title`: Required. Validate it's not empty and within reasonable length.
 * - `content`: Required. The main note body. Validate size to avoid huge payloads.
 * - `tags`: Optional (note the `?`). Defaults to empty array if not provided.
 *
 * Input validation checklist:
 * - Title: non-empty string, max length (e.g., 200 chars)
 * - Content: non-empty string, max length (e.g., 50KB)
 * - Tags: if present, array of strings, each tag max length (e.g., 50 chars)
 * - Total payload size: enforce API Gateway's 10MB limit well before that
 *
 * Authorization:
 * - Extract user ID from JWT (via Cognito or custom authorizer)
 * - Associate the note with that user ID in DynamoDB
 * - Only the creator should be able to read/update/delete their note
 */
export interface CreateNoteInput {
  title: string;
  content: string;
  tags?: string[];
}

/**
 * Input data for updating an existing note.
 *
 * Request lifecycle:
 * 1. Client sends PATCH /notes/{id} with JSON body matching this interface
 * 2. API Gateway passes the body and path parameter to Lambda
 * 3. Lambda validates the input and checks authorization (user owns the note)
 * 4. Lambda reads existing note from DynamoDB
 * 5. Lambda merges updates: only provided fields are changed
 * 6. Lambda updates `updatedAt` timestamp
 * 7. Lambda writes updated note to DynamoDB
 * 8. Lambda returns the updated Note to the client
 *
 * Field explanations:
 * - All fields are optional (note the `?` on each field)
 * - Only fields provided in the request will be updated
 * - `id`, `createdAt` are never updatable (not included here)
 * - Lambda is responsible for updating `updatedAt` automatically
 *
 * Input validation:
 * - At least one field must be provided (reject empty updates)
 * - Validate each provided field using same rules as CreateNoteInput
 * - If tags are provided, they REPLACE the existing tags (not append)
 *
 * Authorization:
 * - Verify the authenticated user owns the note before allowing update
 * - Return 401/403 if unauthorized, 404 if note doesn't exist
 *
 * Serverless note:
 * - Lambda doesn't keep the old note in memory between requests
 * - Each update is a separate invocation: read → validate → merge → write
 */
export interface UpdateNoteInput {
  title?: string;
  content?: string;
  tags?: string[];
}

/**
 * Response structure for listing multiple notes.
 *
 * Request lifecycle:
 * 1. Client sends GET /notes (possibly with query params for pagination)
 * 2. API Gateway triggers Lambda with query string parameters
 * 3. Lambda queries DynamoDB for notes belonging to the authenticated user
 * 4. DynamoDB returns a page of results + optional pagination token
 * 5. Lambda maps DB items to Note objects and wraps in ListNotesResponse
 * 6. Lambda returns JSON to client
 *
 * Field explanations:
 * - `items`: Array of Note objects for the current page. Can be empty array.
 * - `nextToken`: Optional pagination token (opaque string). Present if more
 *   results exist. Client includes this in next request to fetch the next page.
 *
 * Pagination (important for serverless):
 * - DynamoDB has a 1MB per-query result size limit
 * - Use pagination to avoid Lambda timeouts and manage memory
 * - `nextToken` is typically a base64-encoded DynamoDB LastEvaluatedKey
 * - Clients send it as a query parameter: GET /notes?nextToken=abc123
 *
 * Performance considerations:
 * - For large note collections, pagination is mandatory
 * - Consider adding query parameters for filtering (by tag, date range, etc.)
 * - Use DynamoDB GSIs (Global Secondary Indexes) for efficient queries
 * - Remember: Lambda has a max execution time (default 3s, configurable to 15min)
 *
 * Cold start impact:
 * - First request after deployment or inactivity may be slower
 * - Keep response sizes reasonable to minimize serialization overhead
 * - Consider provisioned concurrency for critical list endpoints if needed
 */
export interface ListNotesResponse {
  items: Note[];
  nextToken?: string;
}