version = 0.1

[default.deploy.parameters]
stack_name = "d1-personal-note-stack-main"
resolve_s3 = true
s3_prefix = "d1-personal-note-stack-main"
profile = "terraform-prod"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"main\" DynamoDBTableName=\"d1-personal-note-main-notes\" UserPoolId=\"ap-southeast-1_lNExKXqTR\""
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
